name: build and push docker image API to github

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: 1/4 set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: 2/4 login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 3/4 change image name to lowercase # fail if image name is not lowercase
        run: echo "REPO_LC=cyberius8/carpriceprediction" >> $GITHUB_ENV

      - name: 4/4 build and push
        uses: docker/build-push-action@v6
        with:
          context: api/ # Dockerfile is here
          file: api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LC }}:latest
            ghcr.io/${{ env.REPO_LC }}:${{ github.sha }}
